package com.example.islami

import com.example.islami.models.Chapter

object appConstants {

    var ArSuras= listOf(
        "الفاتحه",
        "البقرة",
        "آل عمران",
        "النساء",
        "المائدة",  
        "الأنعام",
        "الأعراف",
        "الأنفال",
        "التوبة",
        "يونس",
        "هود",
        "يوسف",
        "الرعد",
        "إبراهيم",
        "الحجر",
        "النحل",
        "الإسراء",
        "الكهف",
        "مريم",
        "طه",
        "الأنبياء",
        "الحج",
        "المؤمنون",
        "النّور",
        "الفرقان",
        "الشعراء",
        "النّمل",
        "القصص",
        "العنكبوت",
        "الرّوم",
        "لقمان",
        "السجدة",
        "الأحزاب",
        "سبأ",
        "فاطر",
        "يس",
        "الصافات",
        "ص",
        "الزمر",
        "غافر",
        "فصّلت",
        "الشورى",
        "الزخرف",
        "الدّخان",
        "الجاثية",
        "الأحقاف",
        "محمد",
        "الفتح",
        "الحجرات",
        "ق",
        "الذاريات",
        "الطور",
        "النجم",
        "القمر",
        "الرحمن",
        "الواقعة",
        "الحديد",
        "المجادلة",
        "الحشر",
        "الممتحنة",
        "الصف",
        "الجمعة",
        "المنافقون",
        "التغابن",
        "الطلاق",
        "التحريم",
        "الملك",
        "القلم",
        "الحاقة",
        "المعارج",
        "نوح",
        "الجن",
        "المزّمّل",
        "المدّثر",
        "القيامة",
        "الإنسان",
        "المرسلات",
        "النبأ",
        "النازعات",
        "عبس",
        "التكوير",
        "الإنفطار",
        "المطفّفين",
        "الإنشقاق",
        "البروج",
        "الطارق",
        "الأعلى",
        "الغاشية",
        "الفجر",
        "البلد",
        "الشمس",
        "الليل",
        "الضحى",
        "الشرح",
        "التين",
        "العلق",
        "القدر",
        "البينة",
        "الزلزلة",
        "العاديات",
        "القارعة",
        "التكاثر",
        "العصر",
        "الهمزة",
        "الفيل",
        "قريش",
        "الماعون",
        "الكوثر",
        "الكافرون",
        "النصر",
        "المسد",
        "الإخلاص",
        "الفلق",
        "الناس"
    )
    val englishSurahs = listOf(
        "Al-Fatiha (The Opening)", "Al-Baqarah (The Cow)", "Aal-E-Imran (The Family of Imran)",
        "An-Nisa (The Women)", "Al-Ma'idah (The Table Spread)", "Al-An'am (The Cattle)",
        "Al-A'raf (The Heights)", "Al-Anfal (The Spoils of War)", "At-Tawbah (The Repentance)",
        "Yunus (Jonah)", "Hud (Hud)", "Yusuf (Joseph)", "Ar-Ra'd (The Thunder)",
        "Ibrahim (Abraham)", "Al-Hijr (The Rocky Tract)", "An-Nahl (The Bee)",
        "Al-Isra (The Night Journey)", "Al-Kahf (The Cave)", "Maryam (Mary)", "Taha (Ta-Ha)",
        "Al-Anbiya (The Prophets)", "Al-Hajj (The Pilgrimage)", "Al-Mu'minun (The Believers)",
        "An-Nur (The Light)", "Al-Furqan (The Criterion)", "Ash-Shu'ara (The Poets)",
        "An-Naml (The Ant)", "Al-Qasas (The Stories)", "Al-Ankabut (The Spider)",
        "Ar-Rum (The Romans)", "Luqman (Luqman)", "As-Sajda (The Prostration)",
        "Al-Ahzab (The Confederates)", "Saba (Sheba)", "Fatir (The Originator)",
        "Ya-Sin (Ya Sin)", "As-Saffat (Those Who Set the Ranks)", "Sad (The Letter Sad)",
        "Az-Zumar (The Groups)", "Ghafir (The Forgiver)", "Fussilat (Explained in Detail)",
        "Ash-Shura (The Consultation)", "Az-Zukhruf (The Gold Adornment)",
        "Ad-Dukhan (The Smoke)", "Al-Jathiya (The Crouching)", "Al-Ahqaf (The Wind-Curved Sandhills)",
        "Muhammad (Muhammad)", "Al-Fath (The Victory)", "Al-Hujurat (The Chambers)",
        "Qaf (The Letter Qaf)", "Adh-Dhariyat (The Winnowing Winds)", "At-Tur (The Mount)",
        "An-Najm (The Star)", "Al-Qamar (The Moon)", "Ar-Rahman (The Beneficent)",
        "Al-Waqia (The Inevitable)", "Al-Hadid (The Iron)", "Al-Mujadila (The Pleading Woman)",
        "Al-Hashr (The Exile)", "Al-Mumtahana (She That is to be Examined)", "As-Saff (The Ranks)",
        "Al-Jumu'a (The Congregation)", "Al-Munafiqun (The Hypocrites)", "At-Taghabun (The Mutual Disillusion)",
        "At-Talaq (The Divorce)", "At-Tahrim (The Prohibition)", "Al-Mulk (The Sovereignty)",
        "Al-Qalam (The Pen)", "Al-Haqqa (The Reality)", "Al-Ma'arij (The Ascending Stairways)",
        "Nuh (Noah)", "Al-Jinn (The Jinn)", "Al-Muzzammil (The Enshrouded One)",
        "Al-Muddathir (The Cloaked One)", "Al-Qiyama (The Resurrection)", "Al-Insan (Man)",
        "Al-Mursalat (The Emissaries)", "An-Naba (The Tidings)", "An-Nazi'at (Those Who Drag Forth)",
        "Abasa (He Frowned)", "At-Takwir (The Overthrowing)", "Al-Infitar (The Cleaving)",
        "Al-Mutaffifin (Defrauding)", "Al-Inshiqaq (The Splitting Open)", "Al-Buruj (The Mansions of the Stars)",
        "At-Tariq (The Morning Star)", "Al-Ala (The Most High)", "Al-Ghashiya (The Overwhelming)",
        "Al-Fajr (The Dawn)", "Al-Balad (The City)", "Ash-Shams (The Sun)", "Al-Lail (The Night)",
        "Ad-Duhaa (The Morning Hours)", "Ash-Sharh (The Relief)", "At-Tin (The Fig)",
        "Al-Alaq (The Clot)", "Al-Qadr (The Power)", "Al-Bayyina (The Clear Proof)",
        "Az-Zalzala (The Earthquake)", "Al-Adiyat (The Courser)", "Al-Qari'a (The Calamity)",
        "At-Takathur (The Rivalry in World Increase)", "Al-Asr (The Declining Day)",
        "Al-Humaza (The Traducer)", "Al-Fil (The Elephant)", "Quraysh (Quraysh)",
        "Al-Ma'un (Small Kindnesses)", "Al-Kawthar (Abundance)", "Al-Kafirun (The Disbelievers)",
        "An-Nasr (Divine Support)", "Al-Masad (The Palm Fiber)", "Al-Ikhlas (The Sincerity)",
        "Al-Falaq (The Daybreak)", "An-Nas (Mankind)"
    )
    // List of the number of verses in each Surah (from Surah 1 to Surah 114)
    val verseCounts = listOf(
        7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111, 43, 52, 99, 128, 111,
        110, 98, 135, 112, 78, 118, 64, 77, 227, 93, 88, 69, 60, 34, 30, 73, 54, 45,
        83, 182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29, 18, 45, 60, 49, 62, 55,
        78, 96, 29, 22, 24, 13, 14, 11, 11, 18, 12, 12, 30, 52, 52, 44, 28, 28, 20,
        56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25, 22, 17, 19, 26, 30, 20, 15, 21,
        11, 8, 8, 19, 5, 8, 8, 11, 11, 8, 3, 9, 5, 4, 7, 3, 6, 3, 5, 4, 5, 6
    )

    fun  getchapters():List<Chapter>{
        val chapterlist= mutableListOf<Chapter>()
        for ( i in 0 ..113){
            chapterlist.add(Chapter(
                index=i, titleEn = englishSurahs[i], titleAr = ArSuras[i], verseNumbers = verseCounts[i])
            )


    }
        return chapterlist
}

}